In [13]:
import numpy as np
x = np.array(100)
type(x)

numpy.ndarray

In [17]:
x

array(100)

In [5]:
y=20
type(y)

int

#### 1 D array

In [15]:
y=np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [33]:
y.ndim

1

In [35]:
y.shape

(4,)

#### 2 D array

In [29]:
arr1=np.array([[2,3,4,5],[67,78,89,90]])
arr1

array([[ 2,  3,  4,  5],
       [67, 78, 89, 90]])

In [31]:
arr1.ndim

2

In [37]:
arr1.shape

(2, 4)

In [41]:
arr2=np.array([[12,23,34,45],[67,24,46,27],[98,87,65,54]])
arr2

array([[12, 23, 34, 45],
       [67, 24, 46, 27],
       [98, 87, 65, 54]])

In [43]:
arr2.ndim

2

In [45]:
arr2.shape

(3, 4)

#### 3 D array

In [50]:
arr3=np.array([[[1,2,3,4],[5,6,7,8],[11,12,13,14]],[[15,16,17,18],[19,20,21,22],[23,24,25,26]]])
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [11, 12, 13, 14]],

       [[15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26]]])

In [54]:
arr3.ndim

3

In [56]:
arr3.shape

(2, 3, 4)

### INDEXING AND SLICING OF ARRAYS

#### Indexing and slicing of 1D array

In [70]:
arr1=np.array([1,2,3,4,5,6])
arr1[2]

3

##### syntax[starting index: n-1: increment]

In [74]:
arr1[1:4:1]

array([2, 3, 4])

In [77]:
arr1[1:6:2]

array([2, 4, 6])

In [79]:
arr1[:4]

array([1, 2, 3, 4])

In [83]:
arr1[2:]

array([3, 4, 5, 6])

#### Indexing and slicing of 2D array

In [87]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [89]:
arr2[1][2]

7

In [91]:
arr2[1][1:4:1]

array([6, 7, 8])

#### Indexing and slicing of 3D array

In [94]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3[1][0][2]

9