In [2]:
import numpy as np
arr3=np.array([23,34,45,56,7,6,78])

In [4]:
arr3

array([23, 34, 45, 56,  7,  6, 78])

In [6]:
# replacing element from ndarray
arr3[2]=100
arr3

array([ 23,  34, 100,  56,   7,   6,  78])

In [8]:
arr3[2]+arr3[3]

156

In [10]:
arr3

array([ 23,  34, 100,  56,   7,   6,  78])

In [12]:
# replacing multiple elements from ndarray
arr3[[1,4,-1]]=[20,30,4]

In [14]:
arr3

array([ 23,  20, 100,  56,  30,   6,   4])

In [44]:
#deleting an element 
# np.delete(objectname, indexnumber)

In [46]:
np.delete(arr3, 2)

array([23, 20, 56, 30,  6,  4])

In [48]:
#multiple delete

In [50]:
np.delete(arr3,[1,-1])

array([ 23, 100,  56,  30,   6])

In [52]:
#inserting at the end of the list   (APPEND)

In [54]:
#np.append(objectname,element)

In [56]:
arr3=np.append(arr3,10)

In [58]:
arr3

array([ 23,  20, 100,  56,  30,   6,   4,  10])

In [60]:
#np.insert(objectname, indexnumber, element)

In [62]:
arr3=np.insert(arr3,1,34)
arr3

array([ 23,  34,  20, 100,  56,  30,   6,   4,  10])

In [64]:
# insert multiple elements

In [66]:
arr3=np.insert(arr3,0,[12,13,14])
arr3

array([ 12,  13,  14,  23,  34,  20, 100,  56,  30,   6,   4,  10])

In [68]:
#insert multiple numbers at multiple indexes

In [70]:
arr=np.array([1,2,3,4,5])
index=[1,3,4]
elements=[7,8,9]
arr=np.insert(arr,index,elements)
arr

array([1, 7, 2, 3, 8, 4, 9, 5])

In [72]:
# replacing elements/ updating element

In [74]:
arr4=np.array([23,34,45,56,67])
arr4[2]=100
arr4 

array([ 23,  34, 100,  56,  67])

In [76]:
# objectname[indexnumber]=new_element

In [78]:
# replacing multiple elements

In [80]:
arr5=np.array([1,2,3,4,5])
arr5[[1,2,-1]]=[12,13,14]
arr5

array([ 1, 12, 13,  4, 14])

#### table of two

In [83]:
arr1=np.array([])
for i in range(1,11):
    arr1=np.append(arr1,2*i)
arr1

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [85]:
#where() ---> help to get index number of the data

In [87]:
arr=np.array([12,23,3,45,56,67,78])

In [89]:
# np.where(object with condition)    uses comparison operators ==,!=,<,>,<=,>=

In [91]:
np.where(arr1==56)

(array([], dtype=int64),)

In [93]:
np.where(arr==56)

(array([4]),)

In [95]:
np.where(arr>56)

(array([5, 6]),)

In [97]:
# range is in python is used in numpy as arange()
# np.arange(start, end , increment)
# start=0
# end =n-1
# increment=1

In [99]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])