In [3]:
# Define a NumPy array with the number 0 through 9 and reshape it into 3X3 array. Calculate the cumulative sum along each row.

In [10]:
import numpy as np

In [12]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
y=arr.reshape(3,3)

In [16]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# help(np.cumsum)

In [20]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [22]:
np.cumsum(y,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [24]:
# Generate a 4x4 numpy array with random integers between 1 and 100 . Replace all even numbers with zeroes and odd numbers with ones.

In [26]:
# help(np.random)

In [28]:
import random

In [30]:
a=np.array([])
for i in range(16):
    x=random.randint(1,100)
    a=np.append(a,x)
    
a

array([91., 80., 91., 89., 35.,  5., 34., 13., 88., 70., 72.,  4., 97.,
       10., 22., 16.])

In [32]:
for i in range(16):
    if a[i]%2==0:
        a[i]=0
    else:
        a[i]=1
a

array([1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.])

In [34]:
a.reshape(4,4)

array([[1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [36]:
#  Create a numpy array with the elements ["apple","banana","cherry"] and then find the index of element banana.

In [38]:
arr1=np.array(["apple","banana","cherry"])
arr1

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [40]:
np.where(arr1=="banana")

(array([1]),)

In [42]:
# Define a numpy array containing the numbers 1 through 20 and reshape it into a 4x5 array . compute the mean of each row.

In [44]:
arr2=np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a=arr2.reshape(4,5)

In [48]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
# help(np.mean)

In [52]:
np.mean(a,axis=1)

array([ 3.,  8., 13., 18.])

In [54]:
# Generate a 5x5 numpy array with random integers between 1 and 10 .Replace all values above 5 with 0 and all values below 5 with 1.

In [56]:
import random
arr3=np.array([])
for i in range(25):
    x=random.randint(1,10)
    arr3=np.append(arr3,x)
arr3

array([ 6.,  8., 10.,  9.,  1., 10.,  5.,  1.,  8.,  6.,  3.,  9.,  8.,
        1.,  3., 10.,  8.,  7., 10.,  9.,  1.,  7.,  7.,  8., 10.])

In [58]:
a=arr3.reshape(5,5)

In [60]:
a

array([[ 6.,  8., 10.,  9.,  1.],
       [10.,  5.,  1.,  8.,  6.],
       [ 3.,  9.,  8.,  1.,  3.],
       [10.,  8.,  7., 10.,  9.],
       [ 1.,  7.,  7.,  8., 10.]])

In [62]:
for i in range(5):
    for j in range(5):
        if a[i][j]>5:
            a[i][j]=0
        else:
            a[i][j]=1
a

array([[0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [64]:
# create a numpy array with element ["red","green","blue"] and then count the occurences of each unique element.

In [66]:
r=np.array(["red","green","blue"])
r

array(['red', 'green', 'blue'], dtype='<U5')

In [68]:
w=np.array(["r","e","d","g","n","b","l","u"])
s=w.size
for k in range(s):
    count=0
    for i in range(3):
        for j in r[i]:
            if j==w[k]:
                count=count+1
    print(f"occurence of {w[k]}={count}")
        

occurence of r=2
occurence of e=4
occurence of d=1
occurence of g=1
occurence of n=1
occurence of b=1
occurence of l=1
occurence of u=1


In [70]:
# Define a numpy array containing the numbers 1 through 16 and reshape it into 4X4 array. Extract the diagonal elements and compute their product

In [72]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
for i in range(-3,4):
    x=arr.diagonal(i)
    print(x)
    print(f"product of {i} diagonal ={np.product(x)}")
    

[13]
product of -3 diagonal =13
[ 9 14]
product of -2 diagonal =126
[ 5 10 15]
product of -1 diagonal =750
[ 1  6 11 16]
product of 0 diagonal =1056
[ 2  7 12]
product of 1 diagonal =168
[3 8]
product of 2 diagonal =24
[4]
product of 3 diagonal =4


In [76]:
# help(np.diagonal)

In [78]:
# Generate a 3x3 NumPy array with random floating-point numbers between -1 and 1. Compute the absolute value of each element.

In [80]:
import random

In [82]:
arr=np.array([])
for i in range(9):
    y=random.uniform(1,-1)
    arr=np.append(arr,y)
arr

array([-0.27078797,  0.59544772,  0.01566275,  0.63485264, -0.16637793,
       -0.61954145, -0.85560626, -0.54531489, -0.93108347])

In [84]:
# help(np.random)

In [86]:
# help(np.absolute)

In [88]:
abc=np.absolute(arr)

In [90]:
abc

array([0.27078797, 0.59544772, 0.01566275, 0.63485264, 0.16637793,
       0.61954145, 0.85560626, 0.54531489, 0.93108347])

In [92]:
abc.reshape(3,3)

array([[0.27078797, 0.59544772, 0.01566275],
       [0.63485264, 0.16637793, 0.61954145],
       [0.85560626, 0.54531489, 0.93108347]])

In [94]:
# Create a NumPy array with the elements ["apple", "banana", "cherry"] and then sort them alphabetically in descending order.

In [96]:
arr=np.array(["banana","apple", "cherry"])

In [98]:
# help(np.sort)

In [100]:
arr=np.sort(arr)

In [102]:
arr[: :-1]

array(['cherry', 'banana', 'apple'], dtype='<U6')

In [104]:
# Define a NumPy array containing the numbers 1 through 25 and reshape it into a 5x5 array. Compute the sum of the diagonal elements.

In [106]:
arr=np.arange(1,26).reshape(5,5)

In [108]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
for i in range(-4,5):
    x=arr.diagonal(i)
    print(f"Sum of the diagonal {x} is {np.sum(x)}")

Sum of the diagonal [21] is 21
Sum of the diagonal [16 22] is 38
Sum of the diagonal [11 17 23] is 51
Sum of the diagonal [ 6 12 18 24] is 60
Sum of the diagonal [ 1  7 13 19 25] is 65
Sum of the diagonal [ 2  8 14 20] is 44
Sum of the diagonal [ 3  9 15] is 27
Sum of the diagonal [ 4 10] is 14
Sum of the diagonal [5] is 5


In [112]:
# help(np.sum)

In [114]:
# Generate a 6x6 NumPy array with random integers between 0 and 100. Find the maximum value in each row and replace it with the string "MAX".

In [116]:
import numpy as np
from numpy import random
x=random.randint(1,100,size=(6,6))
x

array([[90, 95, 87, 66, 98, 37],
       [59, 21, 76, 16, 75, 72],
       [75, 18, 69, 38, 58, 81],
       [59, 29, 49, 99, 39, 12],
       [36, 24, 99, 99, 54, 81],
       [71, 23, 54, 27,  6, 84]])

In [118]:
y=np.amax(x,axis=1)

In [120]:
y

array([98, 76, 81, 99, 99, 84])

In [132]:
np.where(x==y)

(array([3, 4, 5]), array([3, 3, 5]))

In [ ]:
# help(np.where)

In [168]:
# Incomplete

In [146]:
# Create the NumPy array with the elements ["cat","dog","bird","cat","dog","fish"] and then count the occurences of each unique element.

In [148]:
# help(np.unique)

In [150]:
arr=np.array( ["cat","dog","bird","cat","dog","fish"])
values, count=np.unique(arr, return_counts= True)
values

array(['bird', 'cat', 'dog', 'fish'], dtype='<U4')

In [152]:
count

array([1, 2, 2, 1])

In [154]:
#  Define a numpy array containing the number 1 through 12 and reshape it into 3X4 array. Calculate the standard deviation of each column.

In [158]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
# help(np.std)

In [164]:
np.std(arr,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [166]:
# Generate a 4X4 numpy array with random integers between -50 and 50. Replace all the negative values with 0 and all positive values with 1

In [170]:
arr=random.randint(-50,50,size=(4,4))
arr

array([[-30,  18,   0,  25],
       [-19,  18, -20,  31],
       [ 33,   9, -46, -37],
       [-34, -18,  28,  23]])

In [172]:
oneD=arr.reshape(-1)

In [174]:
zeros=np.where(oneD<0)

In [188]:
oneD[zeros]=0

In [190]:
ones=np.where(oneD>0)

In [192]:
oneD[ones]=1

In [194]:
oneD

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1])

In [196]:
oneD.reshape(4,4)

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 1]])

In [198]:
# Create a numpy array with the elements ["apple", "banana", "cherry", "apple", "banana"]. Remove duplicates from the array.

In [200]:
arr=np.array(["apple", "banana", "cherry", "apple", "banana"])
np.unique(arr)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [202]:
# Define a numpy array containing the numbers 1 through 16 and reshape it into 4X4 array. Extract elements in the last column.

In [210]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [238]:
# x=arr.reshape(-1)
# x[3::4]

In [242]:
for i in range(4):
    print(arr[i][3])

4
8
12
16


In [244]:
# Generate a 5X5 numpy array with random floating point numbers between 0 and 1. Round each element with the nearest integer.

In [250]:
x=random.random(size=(5,5))
x

array([[0.15709412, 0.35184818, 0.5359812 , 0.55665841, 0.47134394],
       [0.05005512, 0.40387658, 0.43423607, 0.99830071, 0.98754281],
       [0.05047386, 0.94563832, 0.29452549, 0.84119952, 0.78292708],
       [0.42358489, 0.22664775, 0.13435184, 0.09836341, 0.08759726],
       [0.99171121, 0.76949682, 0.8184339 , 0.68548898, 0.15240229]])

In [252]:
np.round(x)

array([[0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [254]:
# Create a numpy array with elements ["red", "green","blue","red","green","blue"].Replace red with orange.

In [258]:
arr=np.array(["red", "green","blue","red","green","blue"])
arr

array(['red', 'green', 'blue', 'red', 'green', 'blue'], dtype='<U5')

In [266]:
for i in range(np.size(arr)):
    if arr[i]=="red":
        arr[i]="orange"
arr

array(['orang', 'green', 'blue', 'orang', 'green', 'blue'], dtype='<U5')

In [268]:
# Define a numpy array containing numbers 1 through 20 and reshape it into 5X4 array. Compute the sum of each column.

In [270]:
arr=np.arange(1,21).reshape(5,4)

In [272]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [274]:
np.sum(arr,axis=0)

array([45, 50, 55, 60])

In [276]:
# Generate a 3X3 numpy array with random integers between 1 and 100. Find the index of maximum value in the array.

In [280]:
arr=random.randint(1,100,size=(3,3))
arr

array([[10, 94, 23],
       [76, 64, 69],
       [52, 82, 72]])

In [282]:
np.amax(arr)

94

In [286]:
np.where(arr==np.amax(arr))

(array([0]), array([1]))

In [288]:
# Generate a nd array of 5X10 with random intergers from 1 to 100. Elements which are divisible by 2 put 0 there ,elements which are not divisible by 2 put 1 there and the elements which are divisible by both 2 and 3 put 2 there.

In [290]:
arr=random.randint(1,100,size=(5,10))
arr

array([[26, 61, 88, 53, 40, 22,  4, 28, 60, 65],
       [67, 96, 40, 33, 71, 76, 40, 36, 55, 52],
       [71, 66, 42, 96, 33, 49, 53, 27, 82, 39],
       [89, 74, 73, 13, 24, 80, 59, 34, 92, 66],
       [11, 91,  1, 31, 36, 99, 35, 37, 49, 65]])

In [312]:
arr[np.where(arr%2==0)]=0
arr[np.where(arr%6==0)]=2
arr[np.where(arr%2!=0)]=1
arr

array([[2, 1, 2, 1, 2, 2, 2, 2, 2, 1],
       [1, 2, 2, 1, 1, 2, 2, 2, 1, 2],
       [1, 2, 2, 2, 1, 1, 1, 1, 2, 1],
       [1, 2, 1, 1, 2, 2, 1, 2, 2, 2],
       [1, 1, 1, 1, 2, 1, 1, 1, 1, 1]])

In [316]:
# Incomplete