In [1]:
import numpy as np
from numpy import random

In [3]:
#  randint()--->generates elements in specific range

In [5]:
zx=random.randint(100)
zx

7

In [7]:
zx=random.randint(10,60)
zx

42

In [9]:
# size parameter in random

In [11]:
zx=random.randint(10,20,size=(2,2))
zx

array([[13, 18],
       [12, 19]])

In [13]:
pq=random.randint(10,100,size=(2,3,4))
pq

array([[[73, 33, 64, 75],
        [90, 25, 43, 55],
        [43, 72, 88, 56]],

       [[69, 49, 27, 61],
        [62, 32, 46, 15],
        [73, 69, 25, 33]]])

In [15]:
# rand()--> generates elements in range from 0 to 1

In [17]:
x=random.rand(10)

In [19]:
x

array([0.45874654, 0.62862035, 0.82152979, 0.71474918, 0.87536184,
       0.99271014, 0.71222896, 0.34704338, 0.00995532, 0.66098573])

In [21]:
x=random.rand(4,2)
x

array([[0.45185664, 0.98029474],
       [0.68834052, 0.53311259],
       [0.56494701, 0.61864162],
       [0.61619782, 0.43707589]])

In [27]:
#  random

In [29]:
pq=random.random()

In [31]:
pq

0.3921136672126184

In [33]:
# choice

In [35]:
ab=random.choice([1,2,3,4,5])
ab

3

In [37]:
zx=random.choice([1,2,3,4,5,6,7,8,9],size=(2,3))

In [39]:
zx

array([[4, 4, 6],
       [1, 6, 2]])

In [41]:
# shuffle

In [43]:
zx=np.array([1,2,3,4,5,6])
random.shuffle(zx)
zx

array([3, 2, 1, 5, 6, 4])