In [1]:
# reshaping in nd arrays
# reshape: this is a methhod that helps to reshape the shape of the data

In [4]:
# 1D ndarray----> 2D ndarray

In [8]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5,6])

In [12]:
arr.ndim

1

In [14]:
# syntax
# np.reshape(objectnamae, shape)
# or
# objectname.reshape(shape)

In [16]:
arr=np.array([1,2,3,4,5])

In [18]:
xyz=np.reshape(arr,(5,1))

In [20]:
xyz.ndim

2

In [22]:
arr=np.array([1,2,3,4,5,6])

In [24]:
np.reshape(arr,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# 2D----> 1D

In [28]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [30]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.reshape(arr,10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# or

In [36]:
xyz=np.reshape(arr,-1)

In [38]:
xyz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# 1d---> 2d

In [42]:
# np.reshape(xyz,(2,-1))

In [44]:
# or

In [46]:
np.reshape(xyz,(-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [48]:
#  -1 autoadjusts the number of columns or number of rows as required the other thing
#  in 1d array -1 gets itself the number of columns by itself only instead of counting the number of elements

In [50]:
# 1d---> 3d

In [52]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])

In [54]:
np.reshape(arr,(5,1,2))

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]],

       [[7, 8]],

       [[9, 0]]])

In [56]:
#  3d--->1d

In [58]:
arr1=np.array([[[ 1,  2]],[[ 3,  4]],[[ 5,  6]],[[ 7,  8]],[[ 9, 10]]])

In [60]:
r=np.reshape(arr1,-1)

In [62]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
# sort() method is used to sort the ndarray in ascending array

In [66]:
arr2=np.array([1,4,3,7,2,6,9])

In [80]:
xyz=np.sort(arr2)

In [82]:
xyz

array([1, 2, 3, 4, 6, 7, 9])

In [84]:
# to do it in desecding order

In [86]:
abc=xyz[ : :-1]

In [88]:
abc

array([9, 7, 6, 4, 3, 2, 1])

In [90]:
# zeros

In [175]:
zx=np.zeros((5,3))

In [177]:
zx

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
# ones

In [183]:
po=np.ones((5,2))

In [185]:
po

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [123]:
# help() method used to know about any function/method

In [ ]:
# we have a function np.eye 
# syntax
# help(functionname)

In [2]:
# help(np.eye)

In [191]:
xyz=np.eye(3,3)

In [193]:
xyz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
#  combining nd arrays

In [129]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

In [131]:
x+y

array([ 6,  8, 10, 12])

In [135]:
#  we will use two method
# concatinate
# vstack

In [141]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [143]:
#  concatenate retirns 1d array

In [145]:
np.vstack((x,y))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
#  vstack returns array over an array. like here it returned 2d array

In [155]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,0,11,12])

In [157]:
np.concatenate((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12])

In [159]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12]])