In [80]:
import pandas as pd
import numpy as np
# import plotly.express as plt
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
data=pd.read_csv("Student_Performance.csv")

In [6]:
data

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [12]:
data.shape

(10000, 6)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB


In [18]:
data.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [20]:
x= data.drop(columns=["Extracurricular Activities","Performance Index"])

In [22]:
x

Hours Studied  Previous Scores  Sleep Hours  \
0                 7               99            9   
1                 4               82            4   
2                 8               51            7   
3                 5               52            5   
4                 7               75            8   
...             ...              ...          ...   
9995              1               49            4   
9996              7               64            8   
9997              6               83            8   
9998              9               97            7   
9999              7               74            8   

      Sample Question Papers Practiced  
0                                    1  
1                                    2  
2                                    2  
3                                    2  
4                                    5  
...                                ...  
9995                                 2  
9996                                 5  
9997                                 5  
9998                                 0  
9999                                 1  

[10000 rows x 4 columns]

In [28]:
y=data[["Performance Index"]]

In [30]:
y.head()

Performance Index
0               91.0
1               65.0
2               45.0
3               36.0
4               66.0

In [34]:
# spliting data in two parts for training  and testing

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [40]:
x_train.shape

(8000, 4)

In [42]:
x_test.shape

(2000, 4)

In [44]:
model=LinearRegression()

In [46]:
# fit--->model training

In [48]:
model.fit(x_train,y_train)

LinearRegression()

In [66]:
b0= model.intercept_

In [68]:
model.coef_

array([[2.85530933, 1.01826507, 0.48209046, 0.19342733]])

In [70]:
b1= 2.85530933
b2= 1.01826507
b3= 0.48209046
b4= 0.19342733

In [56]:
# y = b0 + b1x1 + b2x2 + b3x3 + b4x4

In [58]:
x_test.head()

Hours Studied  Previous Scores  Sleep Hours  \
7006              6               86            4   
1688              3               86            6   
1828              2               67            4   
3632              9               70            8   
3612              6               47            4   

      Sample Question Papers Practiced  
7006                                 2  
1688                                 9  
1828                                 1  
3632                                 4  
3612                                 6

In [60]:
y= -33.76212084 + 2.85530933*2 + 1.01826507*72 + 0.48209046*6 + 0.19342733*4
y

48.92983494

In [72]:
y= b0+ b1*6 +b2*86+ b3*4 + b4*2
y

array([73.25574766])

In [74]:
y_test.head()

Performance Index
7006               73.0
1688               68.0
1828               46.0
3632               67.0
3612               35.0

In [62]:
import joblib

In [64]:
joblib.dump(model, "Student_Performace_predictor.joblib")

['Student_Performace_predictor.joblib']

In [76]:
y_pred= model.predict(x_test)
y_pred

array([[73.25574732],
       [67.00799158],
       [42.2940464 ],
       ...,
       [84.38440331],
       [38.21972809],
       [51.98462986]])

In [84]:
# plt.scatter(x_train,y_train,color="green",label="Train data")
# plt.scatter(x_test,y_test,color="red",label="Test data")
# plt.plot(x_test,y_pred,color="blue",label="Prediction line")
# plt.legend()